[package]
name = "ziquid-samechain-owner-guest"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
sp1-zkvm = "=6.8.1"
ziquid-protocol = { path = "../../../protocol" }
primitive-types = "=0.12.2"
sha2 = "=0.10.9"
ed25519-dalek = { version = "=2.2.0", default-features = false, features = ["std", "zeroize"] }
chacha20poly1305 = "=0.10.1"
zeroize = "=1.9.0"

[profile.dev]
debug = 0
incremental = false

[profile.test]
debug = 0
incremental = false
